package constants

// ReportInfo represents a predefined MarketSurge report.
type ReportInfo struct {
	ID   int
	Name string
}

// PredefinedReports contains all 47 predefined MarketSurge reports.
var PredefinedReports = []ReportInfo{
	{ID: 1, Name: "Top 150 EPS Rating Stocks"},
	{ID: 3, Name: "Top 150 RS Rating Stocks"},
	{ID: 5, Name: "Fastest Growing Companies - Top 150"},
	{ID: 12, Name: "Accumulation Distribution Rating - Stocks Moving Up"},
	{ID: 13, Name: "Accumulation Distribution Rating - Stocks Moving Down"},
	{ID: 16, Name: "NYSE - Short Interest"},
	{ID: 17, Name: "NASDAQ - Short Interest"},
	{ID: 18, Name: "AMEX - Short Interest"},
	{ID: 26, Name: "Top 30 EPS Rating Stocks with High Avg. Volume"},
	{ID: 27, Name: "Top 30 RS Rating Stocks with High Avg. Volume"},
	{ID: 28, Name: "Weekly New High Report"},
	{ID: 29, Name: "Weekly Report of Stocks Approaching or at New High"},
	{ID: 37, Name: "IBD 50 Index"},
	{ID: 38, Name: "IBD New America Index"},
	{ID: 39, Name: "IBD 85-85 Index"},
	{ID: 40, Name: "IBD Big Cap 20"},
	{ID: 46, Name: "197 Industry Groups"},
	{ID: 47, Name: "Today's Industry Performance: NEW HIGHS"},
	{ID: 48, Name: "Today's Industry Performance: NEW LOWS"},
	{ID: 50, Name: "Top 25 Funds over 10 Years"},
	{ID: 51, Name: "Top 25 Industry or Sector Funds Over 3 Years"},
	{ID: 84, Name: "Extended Stocks"},
	{ID: 85, Name: "Accelerating Leaders"},
	{ID: 87, Name: "Decelerating Leaders"},
	{ID: 88, Name: "Top Rated Stocks"},
	{ID: 93, Name: "MarketSurge Growth 250"},
	{ID: 94, Name: "Additions"},
	{ID: 95, Name: "Deletions"},
	{ID: 96, Name: "IPO 1 Year"},
	{ID: 97, Name: "RS Line New High"},
	{ID: 98, Name: "Large Cap"},
	{ID: 99, Name: "Mid Cap"},
	{ID: 100, Name: "Small Cap"},
	{ID: 101, Name: "Technical Strength"},
	{ID: 102, Name: "Fundamental Strength"},
	{ID: 104, Name: "Breaking Out Today"},
	{ID: 105, Name: "Recent Breakouts"},
	{ID: 106, Name: "Near Pivot"},
	{ID: 107, Name: "Tight Areas"},
	{ID: 108, Name: "Power from Pivot"},
	{ID: 109, Name: "Breakaway Gap"},
	{ID: 110, Name: "Earnings - Gap Up"},
	{ID: 111, Name: "Earnings - Gap Down"},
	{ID: 112, Name: "Earnings - Reported"},
	{ID: 113, Name: "Earnings - Upcoming"},
	{ID: 114, Name: "50-Day Break on Volume"},
	{ID: 115, Name: "Pullback to 10-week Line"},
	{ID: 119, Name: "Minervini Trend - 1 Month"},
	{ID: 120, Name: "Minervini Trend - 5 Months"},
	{ID: 121, Name: "RS Line Blue Dot"},
	{ID: 123, Name: "Minervini Trend - 5 Months Wide"},
	{ID: 124, Name: "Bases Forming"},
	{ID: 125, Name: "All Tight Areas"},
	{ID: 126, Name: "All RS Line New High"},
	{ID: 127, Name: "Minervini Trend - 1 - 4 Months"},
	{ID: 130, Name: "Barron's 400"},
	{ID: 131, Name: "Ants List"},
}
